### PR TITLE
Add flag to optionally upload CF template to s3 bucket

### PR DESCRIPTION
**Pull request by mikkeloscar**
When there are many egress routes defined in a cluster, the CF stack template can grow to a size not accepted by Cloudformation anymore. The workaround for this is to upload the template to s3 and reference the s3 url in the CF stack.

This PR adds an optional flag `--cf-template-bucket` which takes the name of an s3 bucket as argument which is used to upload the template.

It's assumed that the s3 bucket lifecycle is managed outside of the controller and that the controller has access to write to the bucket for uploading the templates.

### CODE REVIEW

**Comment by szuecs** [comment]
@mikkeloscar no test?

**Comment by mikkeloscar** [comment]
Will try to come up with some test. It's hard to fully test in unit test as it's mostly AWS s3 and cloudformation interaction that needs to be tested.

**Comment by mikkeloscar** [comment]
@szuecs I added a test for the new code paths. It's mocking the API so it's not testing _that_ much, but better than nothing :)

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
