### PR TITLE
Update to Kubernetes v1.27

### PR DESCRIPTION
**Pull request by mikkeloscar**
* Update to Kubernetes v1.27
* Update vulnerable dependencies

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
merged and released as https://github.com/szuecs/kube-static-egress-controller/releases/tag/v0.2.14

**Pull request merged**
